[package]
name = "hello"
version = "0.1.0"
authors = ["Andrew Heintz <ach3628@rit.edu>"]
edition = "2018"

[lib]
name = "hello"
crate-type = ["cdylib"]

[dependencies]
rand = "0.6"
time = "0.1"
cpython = "0.2"
