# builds the module
target: setup.py cModule.c
	python3 setup.py build

# installs the module
# NOTE: Might need to be run as root
install:
	python3 setup.py install

# cleans up the build
clean:
	rm -r build

